# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 147a7fbe5f83c3c02c26935c604a4cf295fccb228620c2b37b29675b68eda4b53ef43a88f3e8dd3ba5869a7e740581e94831ffd2956fcac4c9114f68497d6814
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  openid_realm: http://webauthserver.137.229.19.187.xip.io
test:
  secret_key_base: 55f6f8200bfc0ba1382ec791531e13810c01f6c6240168dde4a7db2571ef1f40b873e1a8c31837f6818903d63870cbe22df8a5d8b4f3685f8d404d63b15844df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  openid_realm: https://id.gina.alaska.edu
